import React from "react"


export const links = [
    {
      id: 1,
      text: 'home',
      url: '/',
    },
    {
      id: 2,
      text: 'driver standings',
      url: '/driver-standings',
    },
    {
      id: 3,
      text: 'constructor standings',
      url: '/constructor-standings',
    },
    {
      id: 4,
      text: 'calendar',
      url: '/calendar',
    },
  ]
  
  export const f1DriverLinks = [
    {
      id: 1,
      name: 'Lewis Hamilton',
      raceNumber: 44,
      imageUrl: 'src/assets/driverImages/lewis_hamilton.png',
      code: 'HAM',
      bgColor: '#6CD3BF',
    },
    {
      id: 2,
      name: 'Valtteri Bottas',
      raceNumber: 77,
      imageUrl: 'src/assets/driverImages/valtteri_bottas.png',
      code: 'BOT',
      bgColor: '#C92D4B',
    },
    {
      id: 3,
      name: 'Max Verstappen',
      raceNumber: 33,
      imageUrl: 'src/assets/driverImages/max_verstappen.png',
      code: 'VER',
      bgColor: '#303F9F',
    },
    {
      id: 4,
      name: 'Sergio Perez',
      raceNumber: 11,
      imageUrl: 'src/assets/driverImages/sergio_perez.png',
      code: 'PER',
      bgColor: '#303F9F',
    },
    {
      id: 5,
      name: 'Daniel Ricciardo',
      raceNumber: 3,
      imageUrl: 'src/assets/driverImages/daniel_ricciardo.png',
      code: 'RIC',
      bgColor: '#5E8FAA',
    },
    {
      id: 6,
      name: 'Lando Norris',
      raceNumber: 4,
      imageUrl: 'src/assets/driverImages/lando_norris.png',
      code: 'NOR',
      bgColor: '#F58020',
    },
    {
      id: 7,
      name: 'Carlos Sainz',
      raceNumber: 55,
      imageUrl: 'src/assets/driverImages/carlos_sainz.png',
      code: 'SAI',
      bgColor: '#F91536',
    },
    {
      id: 8,
      name: 'Charles Leclerc',
      raceNumber: 16,
      imageUrl: 'src/assets/driverImages/charles_leclerc.png',
      code: 'LEC',
      bgColor: '#F91536',
    },
    {
      id: 9,
      name: 'Pierre Gasly',
      raceNumber: 10,
      imageUrl: 'src/assets/driverImages/pierre_gasly.png',
      code: 'GAS',
      bgColor: '#2293D1',
    },
    {
      id: 10,
      name: 'Yuki Tsunoda',
      raceNumber: 22,
      imageUrl: 'src/assets/driverImages/yuki_tsunoda.png',
      code: 'TSU',
      bgColor: '#5E8FAA',
    },
    {
      id: 11,
      name: 'Fernando Alonso',
      raceNumber: 14,
      imageUrl: 'src/assets/driverImages/fernando_alonso.png',
      code: 'ALO',
      bgColor: '#358C75',
    },
    {
      id: 12,
      name: 'Esteban Ocon',
      raceNumber: 31,
      imageUrl: 'src/assets/driverImages/esteban_ocon.png',
      code: 'OCO',
      bgColor: '#2293D1',
    },
    {
      id: 13,
      name: 'Oscar Piastri',
      raceNumber: 81,
      imageUrl: 'src/assets/driverImages/oscar_piastri.png',
      code: 'PIA',
      bgColor: '#F58020',
    },
    {
      id: 14,
      name: 'Lance Stroll',
      raceNumber: 18,
      imageUrl: 'src/assets/driverImages/lance_stroll.png',
      code: 'STR',
      bgColor: '#358C75',
    },
    {
      id: 15,
      name: 'Alexander Albon',
      raceNumber: 23,
      imageUrl: 'src/assets/driverImages/alexander_albon.png',
      code: 'ALB',
      bgColor: '#37BEDD',
    },
    {
      id: 16,
      name: 'Nico Hulkenberg',
      raceNumber: 27,
      imageUrl: 'src/assets/driverImages/nico_hulkenberg.png',
      code: 'HUL',
      bgColor: '#B6BABD',
    },
    {
      id: 17,
      name: 'Kevin Magnussen',
      raceNumber: 20,
      imageUrl: 'src/assets/driverImages/kevin_magnussen.png',
      code: 'MAG',
      bgColor: '#B6BABD',
    },
    {
      id: 18,
      name: 'Zhou Guanyu',
      raceNumber: 24,
      imageUrl: 'src/assets/driverImages/zhou_guanyu.png',
      code: 'ZHO',
      bgColor: '#C92D4B',
    },
    {
      id: 19,
      name: 'George Russell',
      raceNumber: 63,
      imageUrl: 'src/assets/driverImages/george_russell.png',
      code: 'RUS',
      bgColor: '#6CD3BF',
    },
    {
      id: 20,
      name: 'Liam Lawson',
      raceNumber: 40,
      imageUrl: 'src/assets/driverImages/liam_lawson.png',
      code: 'LAW',
      bgColor: '#5E8FAA',
    },
    {
      id: 21,
      name: 'Logan Sargeant',
      raceNumber: 2,
      imageUrl: 'src/assets/driverImages/logan_sargeant.png',
      code: 'SAR',
      bgColor: '#37BEDD',
    },
    {
      id: 22,
      name: 'Nyck De Vries',
      raceNumber: 47,
      imageUrl: 'src/assets/driverImages/nyck_devries.png',
      code: 'DEV',
      bgColor: '#5E8FAA',
    },
  ];
  
  export const f1ConstructorLinks = [
    {
      id:1,
      name: 'Red Bull',
      bgColor: '#303F9F',
      imageUrl: 'src/assets/teamImages/redbull-racing.png',
    },
    {
      id:2,
      name: 'Mercedes',
      bgColor: '#6CD3BF',
      imageUrl: 'src/assets/teamImages/mercedes.png',
    },
    {
      id:3,
      name: 'Ferrari',
      bgColor: '#F91536',
      imageUrl: 'src/assets/teamImages/ferrari.png',
    },
    {
      id:4,
      name: 'Aston Martin',
      bgColor: '#358C75',
      imageUrl: 'src/assets/teamImages/astonmartin.png',
    },
    {
      id:5,
      name: 'McLaren',
      bgColor: '#F58020',
      imageUrl: 'src/assets/teamImages/mclaren.png',
    },
    {
      id:6,
      name: 'Alpine F1 Team',
      bgColor: '#2293D1',
      imageUrl: 'src/assets/teamImages/alpine.png',
    },
    {
      id:7,
      name: 'Williams',
      bgColor: '#37BEDD',
      imageUrl: 'src/assets/teamImages/williams.png',
    },
    {
      id:8,
      name: 'Haas F1 Team',
      bgColor: '#B6BABD',
      imageUrl: 'src/assets/teamImages/haas.png',
    },
    {
      id:9,
      name: 'Alfa Romeo',
      bgColor: '#C92D4B',
      imageUrl: 'src/assets/teamImages/alfaromeo.png',
    },
    {
      id:10,
      name: 'AlphaTauri',
      bgColor: '#5E8FAA',
      imageUrl: 'src/assets/teamImages/alphatauri.png',
    },
  ];
  
  export const f1CountryCodes = [
    {
      name: 'Monza Circuit',
      country: 'Italy',
      countryCode: 'IT',
      circuitId: 'monza',
    },
    {
      name: 'Silverstone Circuit',
      country: 'UK',
      countryCode: 'GB',
      circuitId: 'silverstone',
    },
    {
      name: 'Circuit de Spa-Francorchamps',
      country: 'Belgium',
      countryCode: 'BE',
      circuitId: 'spa',
    },
    {
      name: 'Hungaroring',
      country: 'Hungary',
      countryCode: 'HU',
      circuitId: 'hungaroring',
    },
    {
      name: 'Sochi Autodrom',
      country: 'Russia',
      countryCode: 'RU',
      circuitId: 'sochi',
    },
    {
      name: 'Circuit of the Americas',
      country: 'United States',
      countryCode: 'US',
      circuitId: 'americas',
    },
    {
      name: 'Miami International Autodrome',
      country: 'USA',
      countryCode: 'US',
      circuitId: 'miami',
    },
    {
      name: 'Miami International Autodrome',
      country: 'USA',
      countryCode: 'US',
      circuitId: 'vegas',
    },
    {
      name: 'Autódromo Hermanos Rodríguez',
      country: 'Mexico',
      countryCode: 'MX',
      circuitId: 'rodriguez',
    },
    {
      name: 'Interlagos Circuit',
      country: 'Brazil',
      countryCode: 'BR',
      circuitId: 'interlagos',
    },
    {
      name: 'Albert Park Circuit',
      country: 'Australia',
      countryCode: 'AU',
      circuitId: 'albert_park',
    },
    {
      name: 'Yas Marina Circuit',
      country: 'UAE',
      countryCode: 'AE',
      circuitId: 'yas_marina',
    },
    {
      name: 'Suzuka Circuit',
      country: 'Japan',
      countryCode: 'JP',
      circuitId: 'suzuka',
    },
    {
      name: 'Shanghai International Circuit',
      country: 'China',
      countryCode: 'CN',
      circuitId: 'shanghai',
    },
    {
      name: 'Baku City Circuit',
      country: 'Azerbaijan',
      countryCode: 'AZ',
      circuitId: 'baku',
    },
    {
      name: 'Circuit de Barcelona-Catalunya',
      country: 'Spain',
      countryCode: 'ES',
      circuitId: 'catalunya',
    },
    {
      name: 'Bahrain International Circuit',
      country: 'Bahrain',
      countryCode: 'BH',
      circuitId: 'bahrain',
    },
    {
      name: 'Jeddah Corniche Circuit',
      country: 'Saudi Arabia',
      countryCode: 'SA',
      circuitId: 'jeddah',
    },
    {
      name: 'Circuit de Monaco',
      country: 'Monaco',
      countryCode: 'MC',
      circuitId: 'monaco',
    },
    {
      name: 'Circuit Gilles Villeneuve',
      country: 'Canada',
      countryCode: 'CA',
      circuitId: 'villeneuve',
    },
    {
      name: 'Red Bull Ring',
      country: 'Austria',
      countryCode: 'AT',
      circuitId: 'red_bull_ring',
    },
    {
      name: 'Circuit Park Zandvoort',
      country: 'Netherlands',
      countryCode: 'NL',
      circuitId: 'zandvoort',
    },
    {
      name: 'Marina Bay Circuit',
      country: 'Singapore',
      countryCode: 'SG',
      circuitId: 'marina_bay',
    },
    {
      name: 'Losail International Circuit',
      country: 'Qatar',
      countryCode: 'QA',
      circuitId: 'losail',
    },
  ];
  
  
  
  
  